name: Test Docker Image

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/test-docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: docker build .
