name: Test and Release

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-22.04

    # Running CI in clean environment is currently not possible: https://github.com/NordicSemiconductor/asset-tracker-cloud-memfault-azure-js/issues/1
    environment:
      name: ci

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List Azure Accounts
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account list --output table

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile source
        run: npx tsc

      - name: Generate Stack ID
        run: |
          RANDOM_STRING=`node -e "const crypto = require('crypto'); process.stdout.write(crypto.randomBytes(Math.ceil(8 * 0.5)).toString('hex').slice(0, 8));"`
          echo "RANDOM_STRING=${RANDOM_STRING}" >> $GITHUB_ENV

      - name: Create resource group
        run: |
          az group create -n memfault-integration-${{ env.RANDOM_STRING }} -l norwayeast
          echo "RESOURCE_GROUP=memfault-integration-${{ env.RANDOM_STRING }}" >> $GITHUB_ENV

      - name: Delete resource group
        if: env.RESOURCE_GROUP != ''
        run: az group delete -n ${{ env.RESOURCE_GROUP }} -y
